package com.example.mall.controller;

import com.example.mall.bean.Comment;
import com.example.mall.bean.Product_brand;
import com.example.mall.exception.ProductNotFoundException;
import com.example.mall.repository.BrandRepository;
import com.example.mall.repository.CommentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller // This means that this class is a Controller
@RequestMapping(path="/brand") // This means URL's start with /demo (after Application path)
public class BrandController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BrandRepository repository;

    //    @RequestParam Integer productId, @RequestParam String name, @RequestParam String description, @RequestParam String keywords, @RequestParam String icon, @RequestParam Integer categoryId, @RequestParam Integer brandId
//            , @RequestParam String email
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewProduct (@RequestBody Map<String,Object> params) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Product_brand brand = new Product_brand();
        String brandId = params.get("brandId").toString();
        brand.setBrandId(brandId);
        String name = params.get("name").toString();
        brand.setName(name);
        String story = params.get("story").toString();
        brand.setStory(story);
        String picture = params.get("picture").toString();
        brand.setPicture(picture);
        repository.save(brand);
        return "Saved";
    }

    @GetMapping(path="/get/")
    public @ResponseBody Iterable<Product_brand> getAllProducts() {
        // This returns a JSON or XML with the users
        return repository.findAll();
    }

    @GetMapping(path = "/get/{id}")
    public @ResponseBody Product_brand getProduct(@PathVariable Integer id) {
        return repository.findById(id).orElseThrow(() -> new ProductNotFoundException(id));
    }

    @PutMapping("/put/{id}")
    Product_brand replaceProduct(@RequestBody Map<String,Object> params, @PathVariable Integer id) {

        return repository.findById(id)
                .map(brand -> {
                    String brandId = params.get("brandId").toString();
                    brand.setBrandId(brandId);
                    String name = params.get("name").toString();
                    brand.setName(name);
                    String story = params.get("story").toString();
                    brand.setStory(story);
                    String picture = params.get("picture").toString();
                    brand.setPicture(picture);
                    return repository.save(brand);
                })
                .orElseGet(() -> {
                    Product_brand brand = new Product_brand();
                    String brandId = params.get("brandId").toString();
                    brand.setBrandId(brandId);
                    String name = params.get("name").toString();
                    brand.setName(name);
                    String story = params.get("story").toString();
                    brand.setStory(story);
                    String picture = params.get("picture").toString();
                    brand.setPicture(picture);
                    return repository.save(brand);
                });
    }

    @DeleteMapping("/delete/{id}")
    void deleteEmployee(@PathVariable Integer id) {
        repository.deleteById(id);
    }

}

