package com.example.mall.controller;
import com.example.mall.bean.Product;
import com.example.mall.exception.ProductNotFoundException;
import com.example.mall.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller // This means that this class is a Controller
@RequestMapping(path="/product") // This means URL's start with /demo (after Application path)
public class ProductController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository repository;

//    @RequestParam Integer productId, @RequestParam String name, @RequestParam String description, @RequestParam String keywords, @RequestParam String icon, @RequestParam Integer categoryId, @RequestParam Integer brandId
//            , @RequestParam String email
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewProduct (@RequestBody Map<String,Object> params) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Product product = new Product();
        String brandId = params.get("brandId").toString();
        product.setBrandId(brandId);
        String categoryId = params.get("categoryId").toString();
        product.setCategoryId(categoryId);
        String description = params.get("description").toString();
        product.setDescription(description);
        String icon = params.get("icon").toString();
        product.setIcon(icon);
        String keywords = params.get("keywords").toString();
        product.setKeywords(keywords);
        String name = params.get("name").toString();
        product.setName(name);
        String productId = params.get("productId").toString();
        product.setProductId(productId);
        repository.save(product);
        return "Saved";
    }

    @GetMapping(path="/get/")
    public @ResponseBody Iterable<Product> getAllProducts() {
        // This returns a JSON or XML with the users
        return repository.findAll();
    }

    @GetMapping(path = "/get/{id}")
    public @ResponseBody Product getProduct(@PathVariable Integer id) {
        return repository.findById(id).orElseThrow(() -> new ProductNotFoundException(id));
    }

    @PutMapping("/put/{id}")
    Product replaceProduct(@RequestBody Map<String,Object> params, @PathVariable Integer id) {

        return repository.findById(id)
                .map(product -> {
                    String brandId = params.get("brandId").toString();
                    product.setBrandId(brandId);
                    String categoryId = params.get("categoryId").toString();
                    product.setCategoryId(categoryId);
                    String description = params.get("description").toString();
                    product.setDescription(description);
                    String icon = params.get("icon").toString();
                    product.setIcon(icon);
                    String keywords = params.get("keywords").toString();
                    product.setKeywords(keywords);
                    String name = params.get("name").toString();
                    product.setName(name);
                    String productId = params.get("productId").toString();
                    product.setProductId(productId);
                    return repository.save(product);
                })
                .orElseGet(() -> {
                    Product product = new Product();
                    String brandId = params.get("brandId").toString();
                    product.setBrandId(brandId);
                    String categoryId = params.get("categoryId").toString();
                    product.setCategoryId(categoryId);
                    String description = params.get("description").toString();
                    product.setDescription(description);
                    String icon = params.get("icon").toString();
                    product.setIcon(icon);
                    String keywords = params.get("keywords").toString();
                    product.setKeywords(keywords);
                    String name = params.get("name").toString();
                    product.setName(name);
                    String productId = params.get("productId").toString();
                    product.setProductId(productId);
                    product.setId(id.toString());
                    return repository.save(product);
                });
    }

    @DeleteMapping("/delete/{id}")
    void deleteProduct(@PathVariable Integer id) {
        repository.deleteById(id);
    }

}
